# -*- coding: utf-8 -*-
"""task2_data_processing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dT2wGWmp6p_uMInRDzI1ZMN-j3vQS5tY
"""

import pandas as pd
import os

# Step 1: Load JSON file
file_path = "/content/hackernews.json"
df = pd.read_json(file_path)

# Print number of rows loaded
print(f"Loaded {len(df)} stories from {file_path}\n")

# Step 2: Clean the Data

df.info()
# 1. Remove duplicate rows based on id
df = df.drop_duplicates(subset="id")
print(f"After removing duplicates: {len(df)}")

# 2. Remove rows with missing important fields
df = df.dropna(subset=["id", "title", "score"])
print(f"After removing nulls: {len(df)}")

# 3. Fix data types
df["score"] = df["score"].astype(int)

# Fill missing num_comments with 0 and convert to int
df["num_comments"] = df["num_comments"].fillna(0).astype(int)

# 4. Remove low-quality stories (score < 5)
df = df[df["score"] >= 5]
print(f"After removing low scores: {len(df)}")

# 5. Remove extra whitespace in title
df["title"] = df["title"].str.strip()

# Step 3: Save cleaned data
os.makedirs("data", exist_ok=True)

output_path = "data/trends_clean.csv"

# Save to CSV
df.to_csv(output_path, index=False)

print(f"\nSaved {len(df)} rows to {output_path}\n")

# Step 4: Summary
print("Top authors (number of stories):")
print(df["author"].value_counts().head(10))

from google.colab import files
files.download("data/trends_clean.csv")

