# -*- coding: utf-8 -*-
"""task4_visualization.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1u3-og01gVEpYsbC78x1f-57ioTsRhnbg
"""

import pandas as pd
import matplotlib.pyplot as plt
import os

# -------------------------------
# Step 1: Load Data + Setup
# -------------------------------

# Load analysed CSV
file_path = "/content/trends_analysed.csv"
df = pd.read_csv(file_path)

# Create outputs folder if it doesn't exist
os.makedirs("outputs", exist_ok=True)

# -------------------------------
# Chart 1: Top 10 Stories by Score
# -------------------------------

# Sort and select top 10
top_stories = df.sort_values(by="score", ascending=False).head(10)

# Shorten long titles
top_stories["short_title"] = top_stories["title"].apply(
    lambda x: x[:50] + "..." if len(x) > 50 else x
)

plt.figure()
plt.barh(top_stories["short_title"], top_stories["score"])
plt.xlabel("Score")
plt.ylabel("Story Title")
plt.title("Top 10 Stories by Score")

# Save chart
plt.savefig("outputs/chart1_top_stories.png")
plt.close()

category_counts = df["author"].value_counts().head(10)

plt.figure()
plt.bar(category_counts.index, category_counts.values)
plt.xlabel("Author")
plt.ylabel("Number of Stories")
plt.title("Top Authors by Number of Stories")
plt.xticks(rotation=45)

plt.savefig("outputs/chart2_categories.png")
plt.close()

plt.figure()

# Split based on popularity
popular = df[df["is_popular"] == True]
not_popular = df[df["is_popular"] == False]

plt.scatter(popular["score"], popular["num_comments"], label="Popular")
plt.scatter(not_popular["score"], not_popular["num_comments"], label="Not Popular")

plt.xlabel("Score")
plt.ylabel("Number of Comments")
plt.title("Score vs Comments")
plt.legend()

plt.savefig("outputs/chart3_scatter.png")
plt.close()

fig, axes = plt.subplots(1, 3, figsize=(18, 5))

# Chart 1
axes[0].barh(top_stories["short_title"], top_stories["score"])
axes[0].set_title("Top Stories")
axes[0].set_xlabel("Score")

# Chart 2
axes[1].bar(category_counts.index, category_counts.values)
axes[1].set_title("Top Authors")
axes[1].set_xlabel("Author")
axes[1].tick_params(axis='x', rotation=45)

# Chart 3
axes[2].scatter(popular["score"], popular["num_comments"], label="Popular")
axes[2].scatter(not_popular["score"], not_popular["num_comments"], label="Not Popular")
axes[2].set_title("Score vs Comments")
axes[2].set_xlabel("Score")
axes[2].set_ylabel("Comments")

fig.suptitle("TrendPulse Dashboard")

plt.tight_layout()

# Save dashboard
plt.savefig("outputs/dashboard.png")
plt.close()
print("✅ All charts saved successfully in 'outputs/' folder")

