# -*- coding: utf-8 -*-
"""mini_project1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WYW7oRasQxmyHVHXDAy1rznaR9-AoEL9
"""

import requests
import json
import os

os.makedirs("data", exist_ok=True)
url = "https://hacker-news.firebaseio.com/v0/topstories.json"
story_ids = requests.get(url).json()

stories = []

for sid in story_ids[:100]:
    data = requests.get(f"https://hacker-news.firebaseio.com/v0/item/{sid}.json").json()

    story = {
        "id": data.get("id"),
        "title": data.get("title"),
        "url": data.get("url"),
        "author": data.get("by"),
        "score": data.get("score"),
        "time": data.get("time"),
        "num_comments": data.get("descendants", 0)
    }

    stories.append(story)

with open("data/hackernews.json", "w") as f:
    json.dump(stories, f, indent=4)

print("JSON created")