# -*- coding: utf-8 -*-
"""task3_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ia0Uya20Hd_0Q7naHVC6FmGwwxOQ2W6P
"""

import pandas as pd
import numpy as np
import os

# -------------------------------
# Step 1: Load and Explore Data
# -------------------------------

file_path = "/content/trends_clean.csv"
df = pd.read_csv(file_path)

# Print shape of dataset
print(f"Loaded data: {df.shape}\n")

# Print first 5 rows
print("First 5 rows:")
print(df.head(), "\n")

# Print average score and comments
avg_score = df["score"].mean()
avg_comments = df["num_comments"].mean()

print(f"Average score   : {avg_score:.2f}")
print(f"Average comments: {avg_comments:.2f}\n")

# -------------------------------
# Step 2: Analysis using NumPy
# -------------------------------

scores = df["score"].values

print("--- NumPy Stats ---")

# Mean, Median, Std deviation
print(f"Mean score   : {np.mean(scores):.2f}")
print(f"Median score : {np.median(scores):.2f}")
print(f"Std deviation: {np.std(scores):.2f}")

# Max and Min score
print(f"Max score    : {np.max(scores)}")
print(f"Min score    : {np.min(scores)}\n")

# Since HackerNews data has no category, use author instead
top_author = df["author"].value_counts().idxmax()
count_author = df["author"].value_counts().max()

print(f"Most stories by author: {top_author} ({count_author} stories)")

# Most commented story
top_story = df.loc[df["num_comments"].idxmax()]
print(f"\nMost commented story: \"{top_story['title']}\" — {top_story['num_comments']} comments\n")

# -------------------------------
# Step 3: Add New Columns
# -------------------------------

# Engagement = comments / (score + 1)
df["engagement"] = df["num_comments"] / (df["score"] + 1)

# is_popular = True if score > average score
df["is_popular"] = df["score"] > avg_score

# -------------------------------
# Step 4: Save the Result
# -------------------------------

# Create folder if not exists
os.makedirs("data", exist_ok=True)

output_path = "data/trends_analysed.csv"

df.to_csv(output_path, index=False)

print(f"Saved to {output_path}")

